language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
# command to run tests
script:
  - make test
  - ./venv/bin/pip install coveralls
after_success:
  - ./venv/bin/coveralls
notifications:
  slack: esnet:UcgwMEeTt4IEFs2OZGwFznH2
